---
title: "596Project_ZhenzhenGe_zg92"
author: "Zhenzhen Ge"
date: "11/27/2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(faraway)
library(tidyverse)
library(rvest)
library(stringr)
library(gdata)
```

## Data scraping and cleaning

```{r, echo=FALSE}
## 2015 US population by state from Wiki
url <- "https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_population"
data_wiki <- url %>%
  read_html() %>%
  html_nodes("table") %>%
  html_table(fill = TRUE)

data_pop <- data_wiki %>% .[[1]]
names(data_pop)[3:4] <- c("State","Pop")
data_pop <- data_pop %>%
  dplyr::select(State, Pop) %>%
  head(n=52)
data_pop$Pop <- as.integer(str_replace_all(data_pop$Pop,",",""))
data_pop$State <- str_replace_all(data_pop$State,"^[[:blank:]]+","")
data_pop <- data_pop %>%
  dplyr::filter(State != "Puerto Rico")

## 2015 personal consumption per capita by state from BEA
data_bea <- read_csv("Data/PCPCE_all.csv")
data_consum <- data_bea %>%
  dplyr::filter(Line == "1") %>%
  dplyr::select(2,27)
names(data_consum) <- c("State","Percap.Consum")
data_all <- left_join(data_pop,data_consum)

## 2015 personal income (Unit: Millions of dollars) by state from BEA
data_bea2 <- data.frame(read.xls("Data/spi0916.xlsx",skip = 3, as.is=TRUE))
data_income <- data_bea2 %>%
  dplyr::select(1:5) 
data_income$Q1r <- as.integer(gsub(",","",data_income$Q1r))
data_income$Q2r <- as.integer(gsub(",","",data_income$Q2r))
data_income$Q3r <- as.integer(gsub(",","",data_income$Q3r))
data_income$Q4r <- as.integer(gsub(",","",data_income$Q4r))
data_income$X <- gsub("^[[:blank:]]+|[.]+","",data_income$X)
data_income$X <- gsub("[[:blank:]]+$","",data_income$X)
data_income <- data_income %>%
  dplyr::mutate(sum = rowSums(.[2:5])) %>%
  dplyr::filter(sum != "NA") %>%
  dplyr::select(X,sum) 
names(data_income) <- c("State","Income")
data_all <- left_join(data_all, data_income)

## 2010 life expectancy by state from Wiki
url_2 <- "https://en.wikipedia.org/wiki/List_of_U.S._states_by_changes_in_life_expectancy,_1985-2010"
data_wiki2 <- url_2 %>%
  read_html() %>%
  html_nodes("table") %>%
  html_table(fill = TRUE)

data_lifeExp <- data_wiki2[[2]]
names(data_lifeExp)[1:2] <- c("State","LifeExp")
data_lifeExp <- data_lifeExp %>%
  dplyr::select(State,LifeExp) 
data_lifeExp$State <- as.character(str_extract_all(data_lifeExp$State, "[A-z ]+"))
data_lifeExp$State <- str_replace_all(data_lifeExp$State, "^[[:blank:]]+","")

data_all <- left_join(data_all, data_lifeExp)


## 2014 rates of high school completion and bachelor's degree attainment
data_ed <- read.xls("Data/tabn104.85.xls", skip = 5, as.is=TRUE)
data_edu <- data_ed %>%
  dplyr::select(1,2,14) %>%
  head(n=51)
names(data_edu) <- c("State","HS.Rate","BA.Rate")
data_edu$State <- gsub("^[[:blank:]]+|[.]+","",data_edu$State)
data_edu$State <- gsub("[[:blank:]]+$","",data_edu$State)

data_all <- left_join(data_all,data_edu)


## US area by state from Wiki
url_3 <- "https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_area"
data_wiki3 <- url_3 %>%
  read_html() %>%
  html_nodes("table") %>%
  html_table(fill = TRUE)
data_area <- data.frame(data_wiki3 %>% .[[1]])
data_area <- data_area %>%
  dplyr::select(1,4) %>%
  tail(n = 60)
names(data_area) <- c("State","Area")
data_area$State <- gsub("^[[:blank:]]+","",data_area$State)
data_area$Area <- as.integer(gsub(",","",data_area$Area))
data_all <- left_join(data_all, data_area)

## 2015 Crime rate from FBI
data_bea2 <- data.frame(read.xls("Data/table_4_crime_in_the_united_states_by_region_geographic_division_and_state_2014-2015.xls",skip = 3, as.is=TRUE))
names(data_bea2)[3] <- "Population"
names(data_bea2)[4] <- "Violent.crime"

tempA <- dplyr::filter(data_bea2, Year == "2015")
tempB <- dplyr::filter(data_bea2, Year == "2014")
data_bea2.pretidy <- cbind(tempB$Area, tempA)

data_bea2.pretidy <- select(data_bea2.pretidy, 1, 5)
data_bea2.pretidy[[2]] <- str_replace_all(data_bea2.pretidy[[2]], ",", "")
data_bea2.pretidy[[1]] <- str_replace_all(data_bea2.pretidy[[1]], "[0-9,]", "")
data_bea2.pretidy[[2]] <- as.integer(data_bea2.pretidy[[2]]) 
names(data_bea2.pretidy) <- c("State", "Violent.Crime")
data_bea2.pretidy[[1]] <- trim(data_bea2.pretidy[[1]])
data_crime <- data_bea2.pretidy

data_all <- left_join(data_all, data_crime)

data_final <- data_all %>% 
  dplyr::mutate(Percap.Income = as.integer((1/4)*Income*1000000/Pop)) %>%
  dplyr::select(-Income)

utils::write.csv(data_final,"Data/rawdata.csv")
```

